import type { Metadata } from 'next';
import localFont from 'next/font/local';

import Sidebar from './components/sidebar';
import './globals.css';
import ReactQueryProvider from './utils/react-client-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex  overflow-hidden`}
      >
        <Sidebar />
        <ReactQueryProvider>
          <main className="relative min-h-screen flex-1  p-8">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
